In [277]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np

In [3]:
print(pd.read_csv("content/TMDB_all_movies.csv").columns)

Index(['id', 'title', 'vote_average', 'vote_count', 'status', 'release_date',
       'revenue', 'runtime', 'budget', 'imdb_id', 'original_language',
       'original_title', 'overview', 'popularity', 'tagline', 'genres',
       'production_companies', 'production_countries', 'spoken_languages',
       'cast', 'director', 'director_of_photography', 'writers', 'producers',
       'music_composer', 'imdb_rating', 'imdb_votes', 'poster_path',
       'keywords', 'certification_us'],
      dtype='str')

In [4]:
df = pd.read_csv(
    "content/TMDB_all_movies.csv",
    usecols=[
        "id",
        "title",
        "release_date",
        "overview",
        "genres",
        "vote_average",
        "vote_count",
        "keywords",
        "cast",
        "director"
    ]
)

print(df.shape)

(1250553, 10)

In [5]:
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'release_date', 'overview',
       'genres', 'cast', 'director', 'keywords'],
      dtype='str')

In [6]:
print(df.overview[3], '\n', df.keywords[3])

Four young friends, while taking a shortcut en route to a local boxing match, witness a brutal murder which leaves them running for their lives.
 drug dealer|chicago, illinois|escape|one night|boxing

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1250553 entries, 0 to 1250552
Data columns (total 10 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   id            1250553 non-null  int64
 1   title         1250539 non-null  str
 2   vote_average  1250553 non-null  float64
 3   vote_count    1250553 non-null  float64
 4   release_date  1116699 non-null  str
 5   overview      1058487 non-null  str
 6   genres        915984 non-null   str
 7   cast          855661 non-null   str
 8   director      1049920 non-null  str
 9   keywords      355497 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 95.4 MB

In [8]:
df = df.query("overview.notna()")

In [9]:
df.cast.isna().sum()

np.int64(317429)

In [10]:
df['cast'] = df.cast.apply(lambda x: x.split(",")[:3] if pd.notna(x) else x)

In [11]:
df['director'] = df.director.apply(lambda x: x.split(",")[0] if pd.notna(x) else x)

In [12]:
df.head(2)

,id,title,vote_average,vote_count,release_date,overview,genres,cast,director,keywords
0,2,Ariel,7.1,382.0,1988-10-21,A Finnish man goes to the city to find a job a...,"Drama, Romance, Crime","[Turo Pajala, Susanna Haavisto, Matti Pellon...",Aki Kaurismäki,"prison|underdog|helsinki, finland|factory work..."
1,3,Shadows in Paradise,7.3,448.0,1986-10-17,"Nikander, a rubbish collector and would-be ent...","Drama, Romance","[Matti Pellonpää, Kati Outinen, Sakari Kuosm...",Aki Kaurismäki,"helsinki, finland|salesclerk|garbage"

In [13]:
df.isna().sum()

id                   0
title                7
vote_average         0
vote_count           0
release_date     99540
overview             0
genres          266117
cast            317429
director        147759
keywords        735663
dtype: int64

In [14]:
df['cast'] = df.cast.fillna("")
df['director'] = df.director.fillna("")

In [15]:
def collapse(x):
    l = []
    for i in x:
        l.append(i.replace(" ", ""))

    return l

In [16]:
df['cast'] = df['cast'].apply(collapse)

In [17]:
df['director'] = df['director'].apply(lambda x: x.replace(" ", ""))

In [18]:
df['genres'] = df.genres.fillna("")
df['keywords'] = df.keywords.fillna("")

In [19]:
df['genres'] = df.genres.apply(lambda x: x.replace(" ", ""))

In [20]:
df.isna().sum()

id                  0
title               7
vote_average        0
vote_count          0
release_date    99540
overview            0
genres              0
cast                0
director            0
keywords            0
dtype: int64

In [21]:


df = df[df.title.notnull()]

In [22]:
df['overview'] = df.overview.apply(lambda x: x.split())
df['genres'] = df.genres.apply(lambda x: x.split(','))

In [23]:
df['keywords'] = df.keywords.str.split("|").apply(collapse)

In [24]:
df.columns

Index(['id', 'title', 'vote_average', 'vote_count', 'release_date', 'overview',
       'genres', 'cast', 'director', 'keywords'],
      dtype='str')

In [25]:
df["genres"].apply(lambda x: x if len(x) < 2 else '')

0
1
2               [Comedy]
3
4          [Documentary]
               ...
1250546               []
1250547               []
1250548               []
1250549               []
1250552               []
Name: genres, Length: 1058480, dtype: object

In [26]:
df['genres'] = df.genres.apply(lambda x: "" if x == [''] else x)
df['keywords'] = df.keywords.apply(lambda x: "" if x == [''] else x)
df['cast'] = df.cast.apply(lambda x: "" if x == [] else x)

In [27]:
df = df[['id', 'title', 'overview', 'genres', 'keywords', 'cast', 'director' ]]

In [28]:
df.isna().sum()

id          0
title       0
overview    0
genres      0
keywords    0
cast        0
director    0
dtype: int64

In [29]:
df.head(  
)

,id,title,overview,genres,keywords,cast,director
0,2,Ariel,"[A, Finnish, man, goes, to, the, city, to, fin...","[Drama, Romance, Crime]","[prison, underdog, helsinki,finland, factorywo...","[TuroPajala, SusannaHaavisto, MattiPellonpää]",AkiKaurismäki
1,3,Shadows in Paradise,"[Nikander,, a, rubbish, collector, and, would-...","[Drama, Romance]","[helsinki,finland, salesclerk, garbage]","[MattiPellonpää, KatiOutinen, SakariKuosmanen]",AkiKaurismäki
2,5,Four Rooms,"[It's, Ted, the, Bellhop's, first, night, on, ...",[Comedy],"[hotel, newyear'seve, witch, bet, sperm, hotel...","[TimRoth, JenniferBeals, DavidProval]",AllisonAnders
3,6,Judgment Night,"[Four, young, friends,, while, taking, a, shor...","[Action, Crime, Drama, Thriller]","[drugdealer, chicago,illinois, escape, onenigh...","[EmilioEstevez, CubaGoodingJr., DenisLeary]",StephenHopkins
4,8,Life in Loops (A Megacities RMX),"[Timo, Novotny, labels, his, new, project, an,...",[Documentary],[megacities],,TimoNovotny

In [30]:
from pandas import DataFrame

ndf = DataFrame()

In [31]:
ndf["overview_text"] = df["overview"].apply(lambda x: " ".join(x))
ndf["genres_text"] = df["genres"].apply(lambda x: " ".join(x))
ndf["keywords_text"] = df["keywords"].apply(lambda x: " ".join(x))
ndf["cast_text"] = df["cast"].apply(lambda x: " ".join(x))
ndf["director_text"] = df["director"].fillna("")

In [32]:
ndf

,overview_text,genres_text,keywords_text,cast_text,director_text
0,A Finnish man goes to the city to find a job a...,Drama Romance Crime,"prison underdog helsinki,finland factoryworker...",TuroPajala SusannaHaavisto MattiPellonpää,AkiKaurismäki
1,"Nikander, a rubbish collector and would-be ent...",Drama Romance,"helsinki,finland salesclerk garbage",MattiPellonpää KatiOutinen SakariKuosmanen,AkiKaurismäki
2,It's Ted the Bellhop's first night on the job....,Comedy,hotel newyear'seve witch bet sperm hotelroom a...,TimRoth JenniferBeals DavidProval,AllisonAnders
3,"Four young friends, while taking a shortcut en...",Action Crime Drama Thriller,"drugdealer chicago,illinois escape onenight bo...",EmilioEstevez CubaGoodingJr. DenisLeary,StephenHopkins
4,Timo Novotny labels his new project an experim...,Documentary,megacities,,TimoNovotny
...,...,...,...,...,...
1250546,Filmmaker Darrin Dick goes on a discovery to u...,,,,
1250547,Adah Sharma's untitled project,,,,
1250548,WHO'S NEXT DYNAMIC GLOVE on U-NEXT Vol.29 take...,,,,
1250549,A hand-drawn animation.,,,,
1250552,Four young skaters spend an afternoon claiming...,,,,

In [33]:
ndf["combined"] = (
    ndf["overview_text"] + " " +
    ndf["genres_text"] + " " +
    ndf["keywords_text"] + " " +
    ndf["cast_text"] + " " +
    ndf["director_text"]
)

In [34]:
ndf.head(2)

,overview_text,genres_text,keywords_text,cast_text,director_text,combined
0,A Finnish man goes to the city to find a job a...,Drama Romance Crime,"prison underdog helsinki,finland factoryworker...",TuroPajala SusannaHaavisto MattiPellonpää,AkiKaurismäki,A Finnish man goes to the city to find a job a...
1,"Nikander, a rubbish collector and would-be ent...",Drama Romance,"helsinki,finland salesclerk garbage",MattiPellonpää KatiOutinen SakariKuosmanen,AkiKaurismäki,"Nikander, a rubbish collector and would-be ent..."

In [35]:
ndf.iloc[6].combined

'Princess Leia is captured and held hostage by the evil Imperial forces in their effort to take over the galactic Empire. Venturesome Luke Skywalker and dashing captain Han Solo team together with the loveable robot duo R2-D2 and C-3PO to rescue the beautiful princess and restore peace and justice in the Empire. Adventure Action ScienceFiction empire galaxy rebellion android hermit smuggling(contraband) freedom rebel rescuemission space planet desert superpower oppression spaceopera wizard totalitarianism quest powerful tuwaderalit MarkHamill HarrisonFord CarrieFisher GeorgeLucas'

In [36]:
fdf = pd.DataFrame({
    'tmdb_id': df['id'],
    'title': df['title'],
    'combined': ndf['combined']
})

In [37]:
fdf

,tmdb_id,title,combined
0,2,Ariel,A Finnish man goes to the city to find a job a...
1,3,Shadows in Paradise,"Nikander, a rubbish collector and would-be ent..."
2,5,Four Rooms,It's Ted the Bellhop's first night on the job....
3,6,Judgment Night,"Four young friends, while taking a shortcut en..."
4,8,Life in Loops (A Megacities RMX),Timo Novotny labels his new project an experim...
...,...,...,...
1250546,1782382,Unforgotten: A Hero’s Story of War,Filmmaker Darrin Dick goes on a discovery to u...
1250547,1782385,Untitled Adah Sharma project,Adah Sharma's untitled project
1250548,1782386,WHO'S NEXT DYNAMIC GLOVE on U-NEXT Vol.29,WHO'S NEXT DYNAMIC GLOVE on U-NEXT Vol.29 take...
1250549,1782387,Imperfect Circles,A hand-drawn animation.
1250552,1782392,Good Old Days,Four young skaters spend an afternoon claiming...

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(
    stop_words="english",
    min_df=5,
    max_df=0.95,
    dtype="float32"
)

In [39]:
X = vectorizer.fit_transform(fdf["combined"])

/home/tesserxt/venvs/mlenv/lib/python3.14/site-packages/sklearn/feature_extraction/text.py:2043: UserWarning: Only (<class 'numpy.float64'>, <class 'numpy.float32'>, <class 'numpy.float16'>) 'dtype' should be used. float32 'dtype' will be converted to np.float64.
  warnings.warn(

In [40]:
X

<Compressed Sparse Row sparse matrix of dtype 'float32'
	with 26890658 stored elements and shape (1058480, 229785)>

In [203]:
from time import perf_counter
from sklearn.metrics.pairwise import cosine_similarity
t0 = perf_counter()

similarities = cosine_similarity(X, X[224])

print(f"Time: {perf_counter() - t0:.2f} seconds")
print(similarities.shape)
print(similarities.nbytes / 1024**2, "MB")

Time: 0.18 seconds
(1058480, 1)
4.03778076171875 MB

In [251]:


query = X[224]

t0 = perf_counter()
scores = X @ query.T
scores = scores.toarray().ravel()



k = 20

idx = np.argpartition(scores, -k)[-k:]
idx = idx[np.argsort(scores[idx])[::-1]]

for i in idx:
   # print(i, scores[i])
    print(fdf.iloc[i].title, i)
    

print(f"Elapsed: {perf_counter() - t0:.2f}s")
print(f"RAM for scores: {scores.nbytes / 1024**2:.2f} MB")

Batman Begins 224
The Dark Knight 116
Keytar Bear 822665
The Dark Knight Rises 32265
Batman 220
Batman Unmasked: The Psychology of The Dark Knight 17982
Batman: Under the Red Hood 25365
Batman: Gotham Knight 7861
A Batman 1050602
Batman: Mask of the Phantasm 8658
The Lego Batman Movie 193399
The Brave and the Bold 661901
The Batman 258025
The Batman: Part II 511122
Batman: The Dark Knight Returns 298128
Batman: Knightfall Part 2: Knightquest 838991
Batman: The Dark Knight Returns, Part 1 77639
Batman: Mystery of the Batwoman 12737
Chase Me 69234
Batgirl 44360
Elapsed: 0.13s
RAM for scores: 4.04 MB

In [250]:
t0 = perf_counter()

nn = NearestNeighbors(
    n_neighbors=20,
    metric="cosine",
    algorithm="brute",
)

nn.fit(X)

distances, indices = nn.kneighbors(X[224])

print(f"Elapsed: {perf_counter() - t0:.2f}s")
print(f"RAM for scores: {scores.nbytes / 1024**2:.2f} MB")

Elapsed: 0.40s
RAM for scores: 4.04 MB

In [ ]:
row = X[224]
words = vectorizer.get_feature_names_out()

for index, value in zip(row.indices, row.data):
    print(words[index], value, index)

In [70]:
fdf[fdf['title'] == 'Batman Begins']

     tmdb_id          title                                           combined
224      272  Batman Begins  Driven by tragedy, billionaire Bruce Wayne ded...

In [ ]:
X.data.nbytes      # actual values
X.indices.nbytes   # column indices
X.indptr.nbytes    # row pointers

107562632

In [266]:
vocab  = vectorizer.vocabulary_

In [254]:
features = vectorizer.get_feature_names_out()

In [82]:
vectorizer.idf_

array([ 8.639897,  6.098342, 12.792904, ..., 12.675121, 12.164295,
       12.926435], shape=(229785,), dtype=float32)

In [62]:
X[0].data

array([0.23469111, 0.10161903, 0.13883717, 0.12698181, 0.15294552,
       0.19995572, 0.21062663, 0.12167978, 0.22918038, 0.17705259,
       0.06878357, 0.111573  , 0.12116665, 0.16633417, 0.26486236,
       0.25589597, 0.23022337, 0.29627666, 0.2117125 , 0.2745675 ,
       0.3548439 , 0.33272925], dtype=float32)

In [276]:
from scipy.sparse import save_npz, load_npz
import joblib

joblib.dump(vectorizer, "artifacts/tfidf_vectorizer.joblib")
save_npz("artifacts/tfidf_X.npz", X)

In [ ]:
# vectorizer = joblib.load("tfidf_vectorizer.joblib")
# X = load_npz("tfidf_X.npz")